version: '3.2'
services:

  tlgrmBot1:
    container_name: tlgrmBot1
    image: golang:1.19
  
    depends_on:
       - postgres
   
    environment:
      ENVIRONMENT: development
    volumes:
      - ./:/app/
    working_dir: /app
    # expose:
    #   - 8181
    # ports:
    #   - '8181:8181'
    command: >
     bash -c "go run  ./cmd/main.go"
   


  postgres:
    container_name: postgres
    image: postgres:13.6
    restart: always
    environment:
      
      POSTGRES_DB: bot
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: user 
      # POSTGRES_HOST: bot
   
    ports:
      - '5432:5432'
    volumes:
        - ./postgres:/var/lib/postgresql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  